OBS_SIZE = 128
SAVE_MODEL_STEPS = 100
ENV_NAME = "environments/mldriver-discrete-steering"
CHECKPOINT_FILE = "mldriver.ckpt"
NUMBER_OF_ACTIONS = 3

GAMMA = 0.99
LR = 0.00005
FRAMES_LOOKBACK = 4
FRAMES_SKIP = 5
BUFFER_SIZE = 16
VALUE_LOSS_K = 0.5
ENTROPY_K = 0.01
USE_DIFF = True
